### ISSUE TITLE
As an instructor, I want to track students level of understanding throughout the class so that I know what material I should elaborate on.

### ISSUE THREAD

**Issue by KatieMacalintal** [csci312-common-v2/class-interactor#25]
## Participant 
![Image](https://github.com/csci312-common-v2/class-interactor/assets/125110058/5a1ec6a8-8e66-4617-9f13-4c08af30c7f0)
### Anticipated Behavior 
- Students can click on special emojis to submit their current level of understanding which will display on the viewer page 
     - 😌: Makes sense
     - 🤨: Uncertain 
     - 😳: Lost 
- Hovering over the emoji will show the description of the level associated with it to avoid clutter on the page
     - Use a Material UI [Popper](https://mui.com/material-ui/react-popper/) or [Popover](https://mui.com/material-ui/react-popover/), although both seem a little big 
- Limit the number of times people can press the same button (every 15 seconds?) 
- Limit how long the level of understanding will be active for (i.e. their selection will reset after 30 seconds or a minute since clicking on one?) 

## Console 
![Image](https://github.com/csci312-common-v2/class-interactor/assets/125110058/409b76bb-6022-4a29-9308-3f712a3c9199)
### Potential Instant Meter Components
- Sparkline: [MUIx](https://mui.com/x/react-charts/sparkline/) or [general](https://www.npmjs.com/package/react-sparklines) 
- [Gauge Chart](https://www.npmjs.com/package/react-gauge-chart): [Example](https://antoniolago.github.io/react-gauge-component/)

### Graphing Over Longer Period of Time
Potential [MUIx Charts](https://mui.com/x/react-charts/) for Longer Term Data 
- **[Bar](https://mui.com/x/react-charts/bars/)**
     - Maybe a stacked graph 
- Will always show data for the last hour and a half? Or should there be a start and end button and it can show over that period of time? The understanding emojis are only active once the admin starts it?

### Other 
- [Line](https://mui.com/x/react-charts/lines/)

## General Questions 
- What values should be associated with each emoji? 
     - Should "Makes sense" be associated with a positive value and "Uncertain" / "Lost" be associated with negative values?

**Comment by mlinderm** [comment]
I think "Grasp Gauge" is a cool name. My immediate reaction on the buttons is to emphasize the text, with the emoji as secondary (i.e., used to communicate to the rest of the class), since the emojis have a less clear meaning.

![Image](https://github.com/csci312-common-v2/class-interactor/assets/419959/e898571d-ba7f-459a-b1e2-73b44d49e770)

The sparkline is a really neat approach for showing the data over time in a compact way. I wonder if we could also use MUI progress components for something analogous to a gauge. Let's start with the instant meter as I think that will be more immediately impactful (and hopefully a little easier to get up and running).

In thinking about your design, especially the data model, we eventually want to be able to think about per-student traces. These would be anonymous but enable looking at understanding over time for a particular individual. W.R.T. the data model, I think that means we don't want to aggregate responses the way we do for the polls (i.e., it would be more similar to questions).

The throttling might be a great place to introduce a custom hook (perhaps something similar to [useThrottle](https://usehooks.com/usethrottle) from useHooks).
